# Generated by Django 4.1.7 on 2023-03-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_licence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
